apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  namespace: default
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/ataicmap02/CCTV_ProVision/efk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - es-cluster-0
          - es-cluster-1
          - es-cluster-2